import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Loader from "./components/Loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="sidebar" data-theme="black">
          <Loader />
          <Sidebar />
          <main className="flex-grow">
            {/* Content goes here */}
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
