export const techIcons = [
  "devicon-java-plain colored",
  "devicon-javascript-plain colored",
  "devicon-react-original colored",
  "devicon-nextjs-plain",
  "devicon-nodejs-plain colored",
  "devicon-nestjs-original colored",
  "devicon-git-plain colored",
  "devicon-docker-plain colored",
  "devicon-amazonwebservices-plain-wordmark colored",
  "devicon-html5-plain colored",
  "devicon-css3-plain colored",
  "devicon-sass-original colored",
  "devicon-mongodb-plain-wordmark colored",
  "devicon-postgresql-plain colored",
  "devicon-mysql-original colored",
  "devicon-redis-plain colored",
  "devicon-tailwindcss-original colored",
  "devicon-redux-original colored",
  "devicon-graphql-plain colored",
  "devicon-materialui-plain colored",
  "devicon-go-original-wordmark colored",
];
